name: flaticon_downloader
description: Flaticon Image & Photo Downloader
version: 0.0.3
repository: https://github.com/thitlwincoder/flaticon_downloader

environment:
  sdk: ^3.8.1

dependencies:
  html: ^0.15.6
  http: ^1.4.0

dev_dependencies:
  very_good_analysis: ^9.0.0
